{% set name = "traja" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/traja-team/traja/archive/v{{ version }}.tar.gz
  sha256: 2a085ec8a25d6840a0914a5bfd68af29ab3785b487c2c9f3e2842a2591b2ad5e

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - pandas
    - matplotlib-base
    - numpy
    - scipy
    - seaborn
    - shapely
    - pillow
    - fastdtw
    - ipython
    - scikit-learn
    - networkx
    - pytorch
    - pytest==6.2.2
    - h5py
    - numba>=0.50.0
    - pyDOE2>=1.3.0
    - statsmodels

test:
  imports:
    - traja

about:
  home: https://github.com/traja-team/traja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Traja is a Python library for trajectory analysis and visualization
  doc_url: https://traja.readthedocs.io
  dev_url: https://github.com/traja-team/traja

extra:
  recipe-maintainers:
    - justinshenk
